development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "<%= ENV['rubyist_email']%>"
  password: "<%= ENV['rubyist_password']%>"
  authentication: :plain
  enable_starttls_auto: true

test:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "<%= ENV['rubyist_email']%>"
  password: "<%= ENV['rubyist_password']%>"
  authentication: :plain
  enable_starttls_auto: true

production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "<%= ENV['rubyist_email']%>"
  password: "<%= ENV['rubyist_password']%>"
  authentication: :plain
  enable_starttls_auto: true
