development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "hoooopo@gmail.com"
  password: "password"
  authentication: :plain
  enable_starttls_auto: true

test:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "hoooopo@gmail.com"
  password: "password"
  authentication: :plain
  enable_starttls_auto: true

production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  user_name: "hoooopo@gmail.com"
  password: "password"
  authentication: :plain
  enable_starttls_auto: true
